cheminfo/rest-on-couch

- src/config/default.js
- src/constants.js
- src/couch/entry.js
- src/index.js
- test/basic.js
- test/data/entryUnicity.js
- test/entryUnicity.js
- test/homedir/test3/config.js
Defaults to 'byOwner' (current behavior) and can be set to 'global'.
When set to 'global', there cannot be two entries with the same id
by different owners.
> feat: add entryUnicity option

- package-lock.json
- src/couch/entry.js
add couch and rest api for a soft delete
This allows to keep the entire document instead of just the id and revision.
> Soft delete

- src/couch/user.js
- src/util/nanoPromise.js
- test/group.js
@targos 
This really patches the getUserGroups method. Previously if a group had no users but was in the default groups, this method would not return it as part of the user's group.
This pull request also fixes a compatibility problem between couchdb 1 and 2. nano does not return the same `reason` when a database does not exist.
> Patch get user groups

- src/import/ImportResult.js
- src/import/saveResult.js
- test/homeDirectories/main/test-new-import/separate/import.js
- test/import/import.js
- test/import/importResult.js
Fixes: https://github.com/cheminfo/rest-on-couch/issues/158
> fix(import): validate that attachment contents is a Buffer

- bin/rest-on-couch-import.js
- package-lock.json
- package.json
It has been superseded by --continuous a long time ago.
BREAKING CHANGE: rest-on-couch-import --watch has been removed.
Use --continuous instead.
> refactor(import bin): remove --watch option

- .dockerignore
- Dockerfile
Inspired by https://github.com/cheminfo/rest-on-couch-docker
Then we can archive that repo and don't need another step to publish the Docker image.
> feat: add Dockerfile to this project

- src/server/server.js
We used to have a BrowserRouter. Now that we are using a HashRouter,
this trick can be removed.
Fixes: https://github.com/cheminfo/rest-on-couch/issues/181
> fix(ui): remove unnecessary index fallback

- src/util/nanoShim.js
- test/api.js
Fixes: https://github.com/cheminfo/rest-on-couch/issues/201
> fix(nanoShim): encode attachment name in CouchDB query

- README.md
- src/config/default.js
- src/server/server.js
This is required since recent versions of Chrome to have a working cross-origin cookie.
> fix: allow to configure SameSite session cookie option

- src/server/middleware/zenodo.js
the Zenodo API limits to 5000 requests / h and in the sandbox we received and error with maximum 100 requests / min. 
@lpatiny suggested to simply use a delay.
> chore: throttle attachment uploads

- src/roc-zenodo/getZenodoDeposition.js
- src/util/orcid.js
- test/unit/orcid.js
The [Zenodo API supports the ORCID id of the creator](https://developers.zenodo.org/#depositions). 
This PR adds support for this optional field and checks if the ORCID is valid. 
I do not know though what the best way to test this is / I didn't see a test for the Zenodo submission.
> feat: added support for ORCID id of creator in Zenodo submission

- src/constants.js
- test/unit/token.js
this allows to create tokens with the addAttachment rights (see the added unit test which failed before making this change)
the better version of https://github.com/cheminfo/rest-on-couch/pull/249
> feat: add addAttachment to globalRightsTypes

- README.md
- src/couch/token.js
- src/server/middleware/couch.js
- test/unit/token.js
we're trying to couple the ELN with some simulation services such as [AiiDAlab](https://aiidalab.materialscloud.org/). For that it would be great to create tokens that also give write access to entries (to put simulation results back into the ELN and close the provenance chain). 
in addition to that i made one minor change to the readme and hint also to the docker compose file which is slightly more convenient than running all the docker commands.
> feat(api): allow to set rights for entry token

- src/couch/attachment.js
- src/couch/entry.js
- src/couch/validate.js
- src/server/middleware/auth.js
- src/server/middleware/couch.js
- test/data/data.js
- test/unit/entry.js
- test/unit/rest-api/user.js
all `PUT` requests failed with unauthorized as the `getUserEmailFromToken` function always returned `anonymous`.  Now it checks for the owner of the token.
Test cases for requests using the tokens have been added.
> fix: token authentication for API requests 

- src/couch/entry.js
- src/server/middleware/couch.js
- test/data/data.js
- test/unit/rest-api/user.js
This time, I tried to make a simple update of the entry, e.g., 
a `PUT` to 
```
http://localhost:3000/db/test/entry/A?token=myUserToken
```
with 
```json
{
"ok": true,
"id": "A",
"rev": "2-b5e45898a38082b584746bd8595e8606",
"$modificationDate": 1614929449107,
"$creationDate": 0
}
```
(see the new unit test). 
But it seems that it ran into the same issue that the token was not passed through to the `getEntriesByUserAndRights` function.
> fix: pass token also for the updateEntry route

- src/couch/entry.js
- src/couch/validate.js
- test/unit/token.js
- test/unit/token2.js
previously the document would be created but it would not be possible to update owners with groups
> fix: fail early when creating document with group but no owner right in token

- src/server/server.js
koa-session won't interpret the parameter correctly otherwise
> fix: convert max age to number

- package.json
Avoids having to update this field when the dependencies are updated.
> chore: use version reference in package overrides

- src/couch/entry.js
- src/design/validateDocUpdate.js
- test/unit/design/validateDocUpdate.js
- test/unit/entry.js
- fix: allow multiple entries with $id of null to be created
- fix: add doc validation to ensure $id is not undefined
> fix: allow multiple entries with null $id

- src/couch/entry.js
- test/unit/entry.js
fix: check $id is defined in getEntryById
> fix: handle $id value of undefined when creating entry

- .ncurc.yml
- eslint.config.mjs
- package-lock.json
- package.json
Koa just published a v3 a few days ago but I prefer not to update it for now and wait that more people have tested the new version.
It contains a big change in the way the query parameters are parsed (goes from `querystring` to builtin `URLSearchParams`).
> chore: update dependencies
