- README.md
- src/config/default.js
- src/server/server.js
> feat: add sessionKey and sessionPath to server options

- src/server/middleware/auth.js
- src/server/routes/auth.js
> feat: add route to change CouchDB password

- package-lock.json
- package.json
- src/connect.js
I tested both #83 and this change. Both work but this is indeed much faster!
> use nano's recommended configuration for localhost heavy lifting

- src/couch/group.js
- src/server/middleware/couch.js
- test/data/data.js
- test/group.js
changes rest api to return all groups when user has global readGroup right
> add getGroups to couch api

- .travis.yml
- package-lock.json
- package.json
- test/data/data.js
- test/data/helper.js
Tests sometimes fail because of timeout.
It seems the db initialization step takes a long time on travis (3 seconds on travis, 70ms on my machine...)
See full logs on travis
> Flaky tests

- README.md
- src/roc-zenodo/index.js
- src/server/middleware/zenodo.js
Also enable publish to test this part
@stropitek
> fix: allow Zenodo readme to be set from the Zenodo entry

- package-lock.json
- package.json
Breaking change is switching to async functions
> chore: update koa-compress to 3.0.0

- README.md
- package-lock.json
- package.json
- src/roc-zenodo/getZenodoDeposition.js
- src/roc-zenodo/index.js
- src/server/middleware/zenodo.js
> Finish zenodo implementation

- package-lock.json
- package.json
- src/server/middleware/util.js
The former has a know security issue and the latter is official and more maintained
> switch for koa-body to koa-bodyparser

- src/config/db.js
- test/homedir/test-new-import/simple/import.js
- test/homedir/test3/config.js
- test/homedir/test3/views/testCustom.js
Allows to put a directory with view definitions in `homedir/dbname/views`
> Multi file config

- README.md
- docs/import.md
- src/import/README.md
@stropitek  Please could you review this code. Especially the last example I have no idea how to do.
> Import readme

- docs/import.md
Closes: https://github.com/cheminfo/rest-on-couch/issues/135
> doc: improve import documentation

- API.md
- src/server/middleware/auth.js
- src/server/middleware/couch.js
- src/server/middleware/decorateError.js
- src/server/middleware/util.js
- src/server/middleware/zenodo.js
- src/server/routes/api.js
- test/rest-api/api.js
Can be optimized later. Allows to get the revision ID of a document without
transferring it completely.
Closes: https://github.com/cheminfo/rest-on-couch/issues/143
> feat: add HEAD for entry to the API

- API.md
Closes: https://github.com/cheminfo/rest-on-couch/issues/228
> doc: add rights route to API documentation

- API.md
- src/server/middleware/couch.js
- src/server/routes/api.js
- test/api.js
sometimes it can be useful to quickly get the version of ROC
> feat: adding api endpoint for ROC version

- .prettierrc.json
- package-lock.json
- package.json
This is to trigger a new release for the Docker image
> fix: update koa dependencies

- API.md
> docs: add document for user/_me/groups endpoint

- package-lock.json
- package.json
- src/couch/entry.js
- src/server/middleware/couch.js
- test/api.js
- test/data/data.js
- test/unit/rest-api/user.js
- chore: update dependencies
- fix: allow tokens to create and delete entries
> Fix create and delete with user token

- package.json
- test/unit/basic.js
The default provider had a bug which produced a bug in the test execution
> fix: run coverage with v8 provider

- .github/workflows/nodejs.yml
- README.md
Closes #303
- chore: remove snyk info from readme
- chore: upload coverage to codecov
- chore: add codecov badge in readme
> coverage badge

- src/couch/entry.js
- test/unit/byOwnerEntryUnicity.js
Closes: https://github.com/cheminfo/rest-on-couch/issues/323
> fix: apply same entry unicity restriction when identified with token

- package-lock.json
- package.json
- src/server/server.js
default compression with brotli was slow and gzip compression is faster when configured with nginx
> feat: remove compression middleware

- src/client/actions/db.js
- src/client/components/GroupCreator.jsx
- src/client/components/GroupDataEditor.jsx
- src/client/components/GroupEditor.jsx
- src/client/components/Groups.jsx
- src/config/default.js
- src/couch/group.js
- src/couch/index.js
- src/couch/init.js
- src/server/middleware/couch.js
- src/server/routes/api.js
- test/data/data.js
- test/data/globalEntryUnicity.js
- test/data/noRights.js
- test/homeDirectories/dev/config.js
- test/homeDirectories/main/config.js
- test/unit/group.js
Closes: https://github.com/cheminfo/rest-on-couch/issues/214
> feat: merge ldap and regular groups together

- src/couch/find.js
- src/server/middleware/couch.js
- src/util/nanoShim.js
streams are activated via the useStreams configuration
> feat: allow to use streams in the find api

- docker-compose.yml
- src/couch/group.js
- src/couch/init.js
- src/couch/util.js
- **chore: remove deprecated `version` property from docker-compose file**
- **fix: implement group migration**
> fix: migrate groups

- .ncurc.yml
- bin/rest-on-couch-import.js
- **fix: make sure the `this` reference is correct when working with `klaw` library**
- **chore: add comments to explain rejected packages**
> fix: improve based on dep upgrade review
